const LEAD_STATUS = {
  NEW: 'NEW',
  CONTACTED: 'CONTACTED',
  QUALIFIED: 'QUALIFIED',
  SITE_VISIT_SCHEDULED: 'SITE_VISIT_SCHEDULED',
  SITE_VISIT_COMPLETED: 'SITE_VISIT_COMPLETED',
  NEGOTIATION: 'NEGOTIATION',
  CONVERTED: 'CONVERTED',
  LOST: 'LOST',
  INVALID: 'INVALID',
};

const LEAD_STATUS_VALUES = Object.values(LEAD_STATUS);

const LEAD_PRIORITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
};

const LEAD_PRIORITY_VALUES = Object.values(LEAD_PRIORITY);

const CONFIGURATION = {
  THREE_BHK: '3BHK',
  FOUR_BHK: '4BHK',
  NOT_SURE: 'NOT_SURE',
};

const CONFIGURATION_VALUES = Object.values(CONFIGURATION);

const CONTACT_TIME = {
  MORNING: 'MORNING',
  AFTERNOON: 'AFTERNOON',
  EVENING: 'EVENING',
};

const CONTACT_TIME_VALUES = Object.values(CONTACT_TIME);

const LEAD_SOURCE = {
  META: 'meta',
  GOOGLE: 'google',
  ORGANIC: 'organic',
  DIRECT: 'direct',
  REFERRAL: 'referral',
  OTHER: 'other',
};

const ACTIVITY_TYPES = {
  LEAD_CREATED: 'LEAD_CREATED',
  STATUS_CHANGED: 'STATUS_CHANGED',
  PRIORITY_CHANGED: 'PRIORITY_CHANGED',
  ASSIGNED: 'ASSIGNED',
  NOTE_ADDED: 'NOTE_ADDED',
  FOLLOW_UP_SCHEDULED: 'FOLLOW_UP_SCHEDULED',
  FOLLOW_UP_COMPLETED: 'FOLLOW_UP_COMPLETED',
  CONTACTED: 'CONTACTED',
  SITE_VISIT_SCHEDULED: 'SITE_VISIT_SCHEDULED',
  SITE_VISIT_COMPLETED: 'SITE_VISIT_COMPLETED',
  CONVERTED: 'CONVERTED',
  MARKED_LOST: 'MARKED_LOST',
  MARKED_INVALID: 'MARKED_INVALID',
  UPDATED: 'UPDATED',
};

module.exports = {
  LEAD_STATUS, LEAD_STATUS_VALUES,
  LEAD_PRIORITY, LEAD_PRIORITY_VALUES,
  CONFIGURATION, CONFIGURATION_VALUES,
  CONTACT_TIME, CONTACT_TIME_VALUES,
  LEAD_SOURCE,
  ACTIVITY_TYPES,
};
