const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  SALES_MANAGER: 'SALES_MANAGER',
  SALES_EXECUTIVE: 'SALES_EXECUTIVE',
};

const ROLE_HIERARCHY = {
  [ROLES.SUPER_ADMIN]: 4,
  [ROLES.ADMIN]: 3,
  [ROLES.SALES_MANAGER]: 2,
  [ROLES.SALES_EXECUTIVE]: 1,
};

const PERMISSIONS = {
  MANAGE_ADMINS: 'manage_admins',
  VIEW_ALL_LEADS: 'view_all_leads',
  EXPORT_LEADS: 'export_leads',
  DELETE_LEADS: 'delete_leads',
  ASSIGN_LEADS: 'assign_leads',
  UPDATE_LEAD_STATUS: 'update_lead_status',
  ADD_NOTES: 'add_notes',
  VIEW_ANALYTICS: 'view_analytics',
  MANAGE_SETTINGS: 'manage_settings',
};

const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.ADMIN]: [
    PERMISSIONS.VIEW_ALL_LEADS,
    PERMISSIONS.EXPORT_LEADS,
    PERMISSIONS.DELETE_LEADS,
    PERMISSIONS.ASSIGN_LEADS,
    PERMISSIONS.UPDATE_LEAD_STATUS,
    PERMISSIONS.ADD_NOTES,
    PERMISSIONS.VIEW_ANALYTICS,
  ],
  [ROLES.SALES_MANAGER]: [
    PERMISSIONS.VIEW_ALL_LEADS,
    PERMISSIONS.ASSIGN_LEADS,
    PERMISSIONS.UPDATE_LEAD_STATUS,
    PERMISSIONS.ADD_NOTES,
    PERMISSIONS.VIEW_ANALYTICS,
  ],
  [ROLES.SALES_EXECUTIVE]: [
    PERMISSIONS.UPDATE_LEAD_STATUS,
    PERMISSIONS.ADD_NOTES,
  ],
};

module.exports = { ROLES, ROLE_HIERARCHY, PERMISSIONS, ROLE_PERMISSIONS };
